package tb;

import com.taobao.android.dinamic.R$id;

/* compiled from: Taobao */
/* loaded from: classes11.dex */
public class m80 {
    public static final String AGET_PREFIX = "aget";
    public static final String AND_PREFIX = "and";
    public static final String APP_STYLE = "appstyle";
    public static final String CONCAT_PREFIX = "concat";
    public static final String CONSTANT_PREFIX = "const";
    public static final String DATA_PREFIX = "data";
    public static final String DEFAULT_TEMPLATE_TYPE = "layout";
    public static final String DGET_PREFIX = "dget";
    public static final String DINAMIC_PREFIX = "$";
    public static final String DINAMIC_PREFIX_AT = "@";
    public static final char DINAMIC_PREFIX_CHAR = '$';
    public static final String DONOT_NEED_BIND_CHILD = "noneNeedBindChild";
    public static final String D_CHECK_BOX = "DCheckBox";
    public static final String D_COUNT_DOWN_TIMER_VIEW = "DCountDownTimerView";
    public static final String D_DEPRECATED = "DdeprecatedView";
    public static final String D_FRAME_LAYOUT = "DFrameLayout";
    public static final String D_HORIZONTAL_SCROLL_LAYOUT = "DHorizontalScrollLayout";
    public static final String D_IMAGE_VIEW = "DImageView";
    public static final String D_LINEAR_LAYOUT = "DLinearLayout";
    public static final String D_LOOP_LINEAR_LAYOUT = "DLoopLinearLayout";
    public static final String D_MODULE_DEFAULT = "default";
    public static final String D_SWITCH = "DSwitch";
    public static final String D_TEXT_INPUT = "DTextInput";
    public static final String D_TEXT_VIEW = "DTextView";
    public static final String D_VIEW = "DView";
    public static final String ELSE_PREFIX = "else";
    public static final int EMPTY_VIEW_TYPE = -1;
    public static final String EQUAL_PREFIX = "eq";
    public static final double ESPINON = 1.0E-9d;
    public static final String FESTIVAL_PREFIX = "festival";
    public static final String FIND_PREFIX = "afnd";
    public static final String FLOAT_BIGGER_EQUAL_PREFIX = "fgte";
    public static final String FLOAT_BIGGER_PREFIX = "fgt";
    public static final String FLOAT_EQUAL = "feq";
    public static final String FLOAT_LITTER_EQUAL_PREFIX = "flte";
    public static final String FLOAT_LITTER_PREFIX = "flt";
    public static final String INT_BIGGER_EQUAL_PREFIX = "igte";
    public static final String INT_BIGGER_PREFIX = "igt";
    public static final String INT_EQUAL = "ieq";
    public static final String INT_LITTER_EQUAL_PREFIX = "ilte";
    public static final String INT_LITTER_PREFIX = "ilt";
    public static final String IS_ELDER = "isElder";
    public static final String LENGTH_PREFIX = "len";
    public static final String LOWER_PREFIX = "lc";
    public static final String MATCH_PREFIX = "if";
    public static final String NOT_PREFIX = "not";
    public static final String OR_PREFIX = "or";
    public static final String RES_AUTO_NAMESPACE = "http://schemas.android.com/apk/res-auto";
    public static final String SIZE_BY_FACTOR = "sizeByFactor";
    public static final String SUBDATA_PREFIX = "subdata";
    public static final String SUBSTR_PREFIX = "substr";
    public static final String TAG_DINAMIC_ROOT_VIEW = "dinamicRootView";
    public static final String TRIM_PREFIX = "trim";
    public static final String TRIPLE_PREFIX = "triple";
    public static final String UPPER_PREFIX = "uc";
    public static boolean a = false;
    public static String b = "1.0";
    public static String c = "__compiler_version__";
    public static String d = "__interpreter_version__";
    public static final int PROPERTY_KEY = R$id.dinamicPropertyTag;
    public static final int VIEW_TYPE_KEY = R$id.dinamicViewType;
    public static final int TAG_ROOT_VIEW_RESULT = R$id.dinamicViewResult;
    public static final int TAG_DINAMIC_BIND_DATA_LIST = R$id.dinamicBindDataList;
    public static final int SUBDATA = R$id.dinamicSubData;
    public static final int LAYOUT_RADII = R$id.dinamicLayoutRadii;
    public static final int VIEW_PARAMS = R$id.dinamicViewParams;
    public static final int KEY_BOARD_LISTENER = R$id.dinamicKeyBoardListener;
    public static final int TEXT_WATCHER = R$id.dinamicTextWatcher;
    public static final am1 NL = new am1();
}
